import type { AlgorithmCase } from "./types";

// Source: https://jperm.net/algs/oll (J Perm Algorithm Trainer data)
export const OLL_ALGORITHMS: AlgorithmCase[] = [
  {
    id: "oll-1",
    displayName: "OLL 1",
    group: "Dot",
    algorithms: ["R U2 R' R' F R F' U2 R' F R F'"],
    probabilityWeight: 2,
  },
  {
    id: "oll-2",
    displayName: "OLL 2",
    group: "Dot",
    algorithms: ["r U r' U2 r U2 R' U2 R U' r'", "y' F R U R' U' F' f R U R' U' f'", "y' F R U R' U' S R U R' U' f'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-3",
    displayName: "OLL 3",
    group: "Dot",
    algorithms: ["r' R2 U R' U r U2 r' U M'", "y F U R U' R' F' U F R U R' U' F'", "y' f R U R' U' f' U' F R U R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-4",
    displayName: "OLL 4",
    group: "Dot",
    algorithms: ["M U' r U2 r' U' R U' R' M'", "y F U R U' R' F' U' F R U R' U' F'", "y' f R U R' U' f' U F R U R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-5",
    displayName: "OLL 5",
    group: "Square Shape",
    algorithms: ["l' U2 L U L' U l", "y2 r' U2 R U R' U r"],
    probabilityWeight: 4,
  },
  {
    id: "oll-6",
    displayName: "OLL 6",
    group: "Square Shape",
    algorithms: ["r U2 R' U' R U' r'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-7",
    displayName: "OLL 7",
    group: "Small Lightning Bolt",
    algorithms: ["r U R' U R U2 r'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-8",
    displayName: "OLL 8",
    group: "Small Lightning Bolt",
    algorithms: ["l' U' L U' L' U2 l", "R U2 R' U2 R' F R F'", "y2 r' U' R U' R' U2 r"],
    probabilityWeight: 4,
  },
  {
    id: "oll-9",
    displayName: "OLL 9",
    group: "Fish Shape",
    algorithms: ["R U R' U' R' F R2 U R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-10",
    displayName: "OLL 10",
    group: "Fish Shape",
    algorithms: ["R U R' U R' F R F' R U2 R'", "y2 r U R' U R U' R' U' r' R (U R U' R')"],
    probabilityWeight: 4,
  },
  {
    id: "oll-11",
    displayName: "OLL 11",
    group: "Small Lightning Bolt",
    algorithms: ["r U R' U R' F R F' R U2 r'", "y2 r' R2 U R' U R U2 R' U M'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-12",
    displayName: "OLL 12",
    group: "Small Lightning Bolt",
    algorithms: ["M' R' U' R U' R' U2 R U' R r'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-13",
    displayName: "OLL 13",
    group: "Knight Move Shape",
    algorithms: ["F U R U' R2 F' R U R U' R'", "r U' r' U' r U r' y' R' U R"],
    probabilityWeight: 4,
  },
  {
    id: "oll-14",
    displayName: "OLL 14",
    group: "Knight Move Shape",
    algorithms: ["R' F R U R' F' R F U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-15",
    displayName: "OLL 15",
    group: "Knight Move Shape",
    algorithms: ["l' U' l L' U' L U l' U l", "y2 r' U' r R' U' R U r' U r"],
    probabilityWeight: 4,
  },
  {
    id: "oll-16",
    displayName: "OLL 16",
    group: "Knight Move Shape",
    algorithms: ["r U r' R U R' U' r U' r'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-17",
    displayName: "OLL 17",
    group: "Dot",
    algorithms: ["F R' F' R2 r' U R U' R' U' M'", "y2 R U R' U R' F R F' U2 R' F R F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-18",
    displayName: "OLL 18",
    group: "Dot",
    algorithms: ["r U R' U R U2 r' r' U' R U' R' U2 r", "y R U2 R' R' F R F' U2 M' (U R U' r')"],
    probabilityWeight: 4,
  },
  {
    id: "oll-19",
    displayName: "OLL 19",
    group: "Dot",
    algorithms: ["r' R U R U R' U' M' R' F R F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-20",
    displayName: "OLL 20",
    group: "Dot",
    algorithms: ["r U R' U' M2 U R U' R' U' M'", "r' R U (R U R' U') M2 U R U' r'"],
    probabilityWeight: 1,
  },
  {
    id: "oll-21",
    displayName: "OLL 21",
    group: "Cross",
    algorithms: ["R U2 R' U' R U R' U' R U' R'", "y R U R' U R U' R' U R U2 R'"],
    probabilityWeight: 2,
  },
  {
    id: "oll-22",
    displayName: "OLL 22",
    group: "Cross",
    algorithms: ["R U2 (R2 U' R2 U' R2) U2 R"],
    probabilityWeight: 4,
  },
  {
    id: "oll-23",
    displayName: "OLL 23",
    group: "Cross",
    algorithms: ["R2 D' R U2 R' D R U2 R", "y2 R2 D R' U2 R D' R' U2 R'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-24",
    displayName: "OLL 24",
    group: "Cross",
    algorithms: ["r U R' U' r' F R F'", "y R U R D R' U' R D' R2"],
    probabilityWeight: 4,
  },
  {
    id: "oll-25",
    displayName: "OLL 25",
    group: "Cross",
    algorithms: ["F' r U R' U' r' F R", "y' R' F R B' R' F' R B"],
    probabilityWeight: 4,
  },
  {
    id: "oll-26",
    displayName: "OLL 26",
    group: "Cross",
    algorithms: ["(R U2 R') U' R U' R'", "y' R' U' R U' R' U2 R"],
    probabilityWeight: 4,
  },
  {
    id: "oll-27",
    displayName: "OLL 27",
    group: "Cross",
    algorithms: ["R U R' U R U2 R'", "y' R' U2 (R U R' U) R"],
    probabilityWeight: 4,
  },
  {
    id: "oll-28",
    displayName: "OLL 28",
    group: "Corners Oriented",
    algorithms: ["r U R' U' r' R U R U' R'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-29",
    displayName: "OLL 29",
    group: "Awkward Shape",
    algorithms: ["R U R' U' R U' R' F' U' F R U R'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-30",
    displayName: "OLL 30",
    group: "Awkward Shape",
    algorithms: ["F R' F R2 U' R' U' R U R' F2", "F U (R U2 R' U') R U2 R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-31",
    displayName: "OLL 31",
    group: "P Shape",
    algorithms: ["R' U' F U R U' R' F' R"],
    probabilityWeight: 4,
  },
  {
    id: "oll-32",
    displayName: "OLL 32",
    group: "P Shape",
    algorithms: ["L U F' U' L' U L F L'", "y2 S R U R' U' R' F R f'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-33",
    displayName: "OLL 33",
    group: "T Shape",
    algorithms: ["R U R' U' R' F R F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-34",
    displayName: "OLL 34",
    group: "C Shape",
    algorithms: ["R U R2 U' R' F R U R U' F'", "R U R' U' B' R' F R F' B"],
    probabilityWeight: 4,
  },
  {
    id: "oll-35",
    displayName: "OLL 35",
    group: "Fish Shape",
    algorithms: ["R U2 R' R' F R F' R U2 R'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-36",
    displayName: "OLL 36",
    group: "W Shape",
    algorithms: ["L' U' L U' L' U L U L F' L' F", "y2 R' U' R U' R' U R U R B' R' B"],
    probabilityWeight: 4,
  },
  {
    id: "oll-37",
    displayName: "OLL 37",
    group: "Fish Shape",
    algorithms: ["F R' F' R U R U' R'", "F R U' R' U' R U R' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-38",
    displayName: "OLL 38",
    group: "W Shape",
    algorithms: ["R U R' U R U' R' U' R' F R F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-39",
    displayName: "OLL 39",
    group: "Big Lightning Bolt",
    algorithms: ["L F' L' U' L U F U' L'", "y2 R B' R' U' R U B U' R'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-40",
    displayName: "OLL 40",
    group: "Big Lightning Bolt",
    algorithms: ["R' F R U R' U' F' U R"],
    probabilityWeight: 4,
  },
  {
    id: "oll-41",
    displayName: "OLL 41",
    group: "Awkward Shape",
    algorithms: ["R U R' U R U2 R' F R U R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-42",
    displayName: "OLL 42",
    group: "Awkward Shape",
    algorithms: ["R' U' R U' R' U2 R F R U R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-43",
    displayName: "OLL 43",
    group: "P Shape",
    algorithms: ["F' U' L' U L F", "R' U' F R' F' R U R"],
    probabilityWeight: 4,
  },
  {
    id: "oll-44",
    displayName: "OLL 44",
    group: "P Shape",
    algorithms: ["F U R U' R' F'", "y2 f R U R' U' f'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-45",
    displayName: "OLL 45",
    group: "T Shape",
    algorithms: ["F R U R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-46",
    displayName: "OLL 46",
    group: "C Shape",
    algorithms: ["R' U' R' F R F' U R"],
    probabilityWeight: 4,
  },
  {
    id: "oll-47",
    displayName: "OLL 47",
    group: "Small L Shape",
    algorithms: ["R' U' R' F R F' R' F R F' U R", "F' L' U' L U L' U' L U F", "y' F U R U' R' F' R U R' U R U2 R'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-48",
    displayName: "OLL 48",
    group: "Small L Shape",
    algorithms: ["F R U R' U' R U R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-49",
    displayName: "OLL 49",
    group: "Small L Shape",
    algorithms: ["r U' r2 U r2 U r2 U' r"],
    probabilityWeight: 4,
  },
  {
    id: "oll-50",
    displayName: "OLL 50",
    group: "Small L Shape",
    algorithms: ["r' U r2 U' r2 U' r2 U r'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-51",
    displayName: "OLL 51",
    group: "I Shape",
    algorithms: ["F U R U' R' U R U' R' F'", "y2 f R U R' U' R U R' U' f'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-52",
    displayName: "OLL 52",
    group: "I Shape",
    algorithms: ["R U R' U R U' B U' B' R'", "y2 R' F' U' F U' (R U R' U) R", "R U R' U R U' y R U' R' F'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-53",
    displayName: "OLL 53",
    group: "Small L Shape",
    algorithms: ["l' U2 L U L' U' L U L' U l", "y2 r' U2 (R U R' U') R U R' U r", "y r' U' R U' R' U R U' R' U2 r"],
    probabilityWeight: 4,
  },
  {
    id: "oll-54",
    displayName: "OLL 54",
    group: "Small L Shape",
    algorithms: ["(r U2 R' U') R U R' U' R U' r'", "y r U R' U R U' R' U R U2 r'"],
    probabilityWeight: 4,
  },
  {
    id: "oll-55",
    displayName: "OLL 55",
    group: "I Shape",
    algorithms: ["R' F R U R U' R2 F' R2 U' R' U R U R'", "y R U2 R2 U' R U' R' U2 F R F'"],
    probabilityWeight: 2,
  },
  {
    id: "oll-56",
    displayName: "OLL 56",
    group: "I Shape",
    algorithms: ["(r' U' r) U' R' U R U' R' U R r' U r", "(r U r') U R U' R' U R U' R' (r U' r')", "(r U r') U R U' R' U R U' M' U' r'"],
    probabilityWeight: 2,
  },
  {
    id: "oll-57",
    displayName: "OLL 57",
    group: "Corners Oriented",
    algorithms: ["R U R' U' M' U R U' r'"],
    probabilityWeight: 2,
  },
];
