import type { AlgorithmCase } from "./types";

// Source: https://jperm.net/algs/pll (J Perm Algorithm Trainer data)
export const PLL_ALGORITHMS: AlgorithmCase[] = [
  {
    id: "pll-h",
    displayName: "PLL H",
    group: "Edges Only",
    algorithms: ["M2 U M2 U2 M2 U M2", "M2 U' M2 U2 M2 U' M2"],
    probabilityWeight: 1,
  },
  {
    id: "pll-z",
    displayName: "PLL Z",
    group: "Edges Only",
    algorithms: ["M' U M2 U M2 U M' U2 M2", "y M' U' M2 U' M2 U' M' U2 M2", "y M2 U M2 U M' U2 M2 U2 M'", "M2 U' M2 U' M' U2 M2 U2 M'"],
    probabilityWeight: 2,
  },
  {
    id: "pll-ua",
    displayName: "PLL Ua",
    group: "Edges Only",
    algorithms: ["M2 U M U2 M' U M2", "R U' R U R U R U' R' U' R2", "y2 R2 U' R' U' R U R U R U' R"],
    probabilityWeight: 4,
  },
  {
    id: "pll-ub",
    displayName: "PLL Ub",
    group: "Edges Only",
    algorithms: ["M2 U' M U2 M' U' M2", "R2 U (R U R' U') R' U' R' U R'", "y2 R' U R' U' R' U' (R' U R U) R2", "y2 R' U R' U' R3 U' (R' U R U) R2"],
    probabilityWeight: 4,
  },
  {
    id: "pll-aa",
    displayName: "PLL Aa",
    group: "Adjacent Corner Swap",
    algorithms: ["x L2 D2 L' U' L D2 L' U L'", "y' x' L' U L' D2 L U' L' D2 L2", "y x R' U R' D2 R U' R' D2 R2", "y2 x' R2 D2 R' U' R D2 R' U R'"],
    probabilityWeight: 4,
  },
  {
    id: "pll-ab",
    displayName: "PLL Ab",
    group: "Adjacent Corner Swap",
    algorithms: ["x' L2 D2 L U L' D2 L U' L", "y x L U' L D2 L' U L D2 L2", "y2 x R2 D2 R U R' D2 R U' R", "y' x' R U' R D2 R' U R D2 R2"],
    probabilityWeight: 4,
  },
  {
    id: "pll-e",
    displayName: "PLL E",
    group: "Diagonal Corner Swap",
    algorithms: ["x' L' U L D' L' U' L D L' U' L D' L' U L D", "x' R U' R' D R U R' D' R U R' D R U' R' D'"],
    probabilityWeight: 2,
  },
  {
    id: "pll-f",
    displayName: "PLL F",
    group: "Adjacent Corner Swap",
    algorithms: ["R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R"],
    probabilityWeight: 4,
  },
  {
    id: "pll-ja",
    displayName: "PLL Ja",
    group: "Adjacent Corner Swap",
    algorithms: ["x R2 F R F' R U2 r' U r U2", "y2 L' U' L F L' U' L U L F' L2 U L", "y' R' U L' U2 R U' R' U2 R L"],
    probabilityWeight: 4,
  },
  {
    id: "pll-jb",
    displayName: "PLL Jb",
    group: "Adjacent Corner Swap",
    algorithms: ["R U R' F' R U R' U' R' F R2 U' R'"],
    probabilityWeight: 4,
  },
  {
    id: "pll-ra",
    displayName: "PLL Ra",
    group: "Adjacent Corner Swap",
    algorithms: ["R U' R' U' R U R D R' U' R D' R' U2 R'", "R U R' F' R U2 R' U2 R' F R U R U2 R'", "y' L U2 L' U2 L F' L' U' L U L F L2"],
    probabilityWeight: 4,
  },
  {
    id: "pll-rb",
    displayName: "PLL Rb",
    group: "Adjacent Corner Swap",
    algorithms: ["R2 F R U R U' R' F' R U2 R' U2 R", "y' R' U2 R U2 R' F R U R' U' R' F' R2", "R' U2 R' D' R U' R' D R U R U' R' U' R"],
    probabilityWeight: 4,
  },
  {
    id: "pll-t",
    displayName: "PLL T",
    group: "Adjacent Corner Swap",
    algorithms: ["R U R' U' R' F R2 U' R' U' (R U R') F'"],
    probabilityWeight: 4,
  },
  {
    id: "pll-y",
    displayName: "PLL Y",
    group: "Diagonal Corner Swap",
    algorithms: ["F R U' R' U' R U R' F' R U R' U' R' F R F'", "F R' F R2 U' R' U' R U R' F' R U R' U' F'"],
    probabilityWeight: 4,
  },
  {
    id: "pll-v",
    displayName: "PLL V",
    group: "Diagonal Corner Swap",
    algorithms: ["R' U R' U' y R' F' R2 U' R' U R' F R F", "R' U R' U' R D' R' D R' U D' R2 U' R2 D R2", "z D' R2 D R2 U R' D' R U' R U R' D R U' z'", "R U2 R' D R U' R U' R U R2 D R' U' R D2", "x' R' F R F' U R U2 R' U' R U' R' U2 R U R' U'"],
    probabilityWeight: 4,
  },
  {
    id: "pll-na",
    displayName: "PLL Na",
    group: "Diagonal Corner Swap",
    algorithms: ["R U R' U R U R' F' R U R' U' R' F R2 U' R' U2 R U' R'", "z U R' D R2 U' R D' U R' D R2 U' R D'"],
    probabilityWeight: 1,
  },
  {
    id: "pll-nb",
    displayName: "PLL Nb",
    group: "Diagonal Corner Swap",
    algorithms: ["R' (U R U' R') F' U' F R U R' F R' F' R U' R", "z D' R U' R2 D R' U D' R U' R2 D R' U"],
    probabilityWeight: 1,
  },
  {
    id: "pll-ga",
    displayName: "PLL Ga",
    group: "Adjacent Corner Swap",
    algorithms: ["R2 U R' U R' U' R U' R2 (U' D) R' U R D'", "R2 u R' U R' U' R u' R2 y' R' U R"],
    probabilityWeight: 4,
  },
  {
    id: "pll-gb",
    displayName: "PLL Gb",
    group: "Adjacent Corner Swap",
    algorithms: ["R' U' R (U D') R2 U R' U R U' R U' R2 D", "y F' U' F R2 u R' U R U' R u' R2"],
    probabilityWeight: 4,
  },
  {
    id: "pll-gc",
    displayName: "PLL Gc",
    group: "Adjacent Corner Swap",
    algorithms: ["R2 U' R U' R U R' U R2 (U D') R U' R' D", "y2 R2 F2 R U2 R U2 R' F R U R' U' R' F R2", "R2 u' R U' R U R' u R2 y R U' R'"],
    probabilityWeight: 4,
  },
  {
    id: "pll-gd",
    displayName: "PLL Gd",
    group: "Adjacent Corner Swap",
    algorithms: ["R U R' (U' D) R2 U' R U' R' U R' U R2 D'", "R U R' y' R2 u' R U' R' U R' u R2"],
    probabilityWeight: 4,
  },
];
