/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as PllRouteImport } from './pll'
import { Route as OllRouteImport } from './oll'
import { Route as IndexRouteImport } from './index'

const PllRoute = PllRouteImport.update({
  id: '/pll',
  path: '/pll',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./pll.lazy').then((d) => d.Route))
const OllRoute = OllRouteImport.update({
  id: '/oll',
  path: '/oll',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./oll.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/oll': typeof OllRoute
  '/pll': typeof PllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/oll': typeof OllRoute
  '/pll': typeof PllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/oll': typeof OllRoute
  '/pll': typeof PllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/oll' | '/pll'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/oll' | '/pll'
  id: '__root__' | '/' | '/oll' | '/pll'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OllRoute: typeof OllRoute
  PllRoute: typeof PllRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pll': {
      id: '/pll'
      path: '/pll'
      fullPath: '/pll'
      preLoaderRoute: typeof PllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oll': {
      id: '/oll'
      path: '/oll'
      fullPath: '/oll'
      preLoaderRoute: typeof OllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OllRoute: OllRoute,
  PllRoute: PllRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
